### ISSUE TITLE
Unable to compile under Linux

### ISSUE THREAD

**Issue by santiago046** [xan1242/PSPModBase#1]
First, I am new to PSP development, so I apologize if I miss something obvious. I followed the instructions in README.md to test the project before working on my plugin, but I could only compile PSPModBaseBoot — PSPModBase fails to build.

I am using the latest PSPDEV toolchain, downloaded from [here](https://github.com/pspdev/pspdev/releases/latest/).

When trying `make -C PSPModBase/source/PSPModBase`, it fails outputting:
```
make: Entering directory '/root/PSPModBase/source/PSPModBase'
psp-gcc -I. -I/usr/local/pspdev/psp/include -I/usr/local/pspdev/psp/sdk/include -O2 -Os -G0 -Wall -fshort-wchar -fno-pic -mno-check-zero-division -fpack-struct=16 -D_PSP_FW_VERSION=600   -c -o main.o main.c
main.c: In function ‘CheckModulesPSP’:
main.c:157:68: error: passing argument 2 of ‘kuKernelFindModuleByName’ from incompatible pointer type [-Wincompatible-pointer-types]
  157 |     int kuErrCode = kuKernelFindModuleByName(MODULE_NAME_INTERNAL, &mod);
      |                                                                    ^~~~
      |                                                                    |
      |                                                                    SceModule2 *
In file included from main.c:24:
/usr/local/pspdev/psp/sdk/include/kubridge.h:104:56: note: expected ‘SceModule *’ but argument is of type ‘SceModule2 *’
  104 | int kuKernelFindModuleByName(char *modname, SceModule *mod);
      |                                             ~~~~~~~~~~~^~~
main.c:162:55: error: passing argument 2 of ‘kuKernelFindModuleByName’ from incompatible pointer type [-Wincompatible-pointer-types]
  162 |     kuErrCode = kuKernelFindModuleByName(MODULE_NAME, &this_module);
      |                                                       ^~~~~~~~~~~~
      |                                                       |
      |                                                       SceModule2 *
/usr/local/pspdev/psp/sdk/include/kubridge.h:104:56: note: expected ‘SceModule *’ but argument is of type ‘SceModule2 *’
  104 | int kuKernelFindModuleByName(char *modname, SceModule *mod);
      |                                             ~~~~~~~~~~~^~~
make: *** [<builtin>: main.o] Error 1
make: Leaving directory '/root/PSPModBase/source/PSPModBase'
```

After casting `SceModule2 *` to `SceModule *`, it only uncovered additional compilation errors. You can see the errors and the steps I followed in this [Colab Notebook](https://gist.github.com/santiago046/9b9f3208242b7cc4e53a43628799f8ec).

**Comment by xan1242** [comment]
Something must've been updated since the last time I made this repo, hence causing this error.

It's been a while since I've last played with this, so my memory is a bit hazy.

It seems that the `psp-gcc` version has been updated from `11.2.0` to `14.1.0`, as well as a bunch of other headers/types causing this cascade of errors. It probably became a lot more strict on types since then.

I wonder if you can even compile my other project from your end: https://github.com/xan1242/TF-MultiFix

If you can compile it, then that means some of this injection code is just plain bad and needs rewriting.

Truth be told, the original implementation of some of this code (e.g. the injector and pattern detector) isn't the greatest, so I made my own mini injector code in that other project.

Also, how and where did you obtain the CFW headers (kubridge.h and others)?

**Comment by santiago046** [comment]
TF-MultiFixBoot was successful compiled here, but not TF6-MultiFix. Initially, it had the same incompatible type of `SceModule *`. Trying to cast made it to throw:
```
../../includes/psp/minjector.c: In function ‘minj_DiscoverPtr’:
../../includes/psp/minjector.c:243:16: warning: comparison between pointer and integer
  243 |     if (ptrLUI == NULL)
      |                ^~
../../includes/psp/minjector.c:244:16: error: returning ‘void *’ from a function with return type ‘uintptr_t’ {aka ‘unsigned int’} makes integer from pointer without a cast [-Wint-conversion]
  244 |         return NULL;
      |                ^~~~
../../includes/psp/minjector.c:247:12: error: assignment to ‘uintptr_t’ {aka ‘unsigned int’} from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
  247 |     ptrADD = NULL;
      |            ^
../../includes/psp/minjector.c:260:16: warning: comparison between pointer and integer
  260 |     if (ptrADD == NULL)
      |                ^~
../../includes/psp/minjector.c:261:16: error: returning ‘void *’ from a function with return type ‘uintptr_t’ {aka ‘unsigned int’} makes integer from pointer without a cast [-Wint-conversion]
  261 |         return NULL;
      |                ^~~~
```

> Also, how and where did you obtain the CFW headers (kubridge.h and others)?

I got them from https://github.com/uofw/uofwinst. I took a look now and it seems that some headers are already included in the PSPDEV toolchain, so I just copied `system_ctrl.h`, `libpspsystemctrl_user.a` and `libpspsystemctrl_kernel.a` files instead of everything from uofwinst's `includes` and `libs` before trying to compile TF-MultiFix.
